apiVersion: apps/v1
kind: Deployment
metadata:
  name: corewebappdemo-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CoreWebAppDemo
  template:
    metadata:
      labels:
        app: CoreWebAppDemo
    spec:
      containers:
      - name: corewebappdemo
        image: corewebappdemocr.azurecr.io/corewebappdemoimage
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: corewebappdemosecret
---
apiVersion: v1
kind: Service
metadata:
  name: corewebappdemo  
spec:
  type: LoadBalancer
  ports:
  -port: 5000
  selector:
    app: corewebappdemo